# Parameters to adjust

# Remove bright detections
amplitude_tolerance = 1.5

# Remove large detections
sigmax_tolerance = 1.1
sigmay_tolerance = 2.5
sigmaz_tolerance = 1.45

# Remove low detection quality (high error) detections
quality_threshold_mu = 1.1
quality_threshold_sigma = 1.22